name: Azure Container Apps Deployment

on:
  push:
    branches:
      - main

env:
  LOGIN_SERVER: rustrocketwebservice.azurecr.io
  IMAGE_NAME: rocket-webserver-rs
  VERSION: v0.0.6

jobs:
  build-and-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ env.LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Deploy Azure Container App
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          resourceGroup: container-rg
          imageToBuild: ${{ env.LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          containerAppEnvironment: container-apps-environment-consumption-only
          containerAppName: rocket-webservice-container-app
          environmentVariables: USER=my_user PASSWORD=my_password
