name: Azure Docker Container Deployment

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: azure/docker-login@v2
        with:
          login-server: rustrocketwebservice.azurecr.io
          username: rustrocketwebservice
          password: ${{ secrets.ACR_PASSWORD }}

      - run: |
          docker build . -t rustrocketwebservice.azurecr.io/rocket-webserver-rs:${{ github.sha }}
          docker push rustrocketwebservice.azurecr.io/rocket-webserver-rs:${{ github.sha }}
